version: '3.1'
services:
  mariadb:
    container_name: "mariadbProducts"
    image: mariadb:latest
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb1234"
      MYSQL_DATABASE: "productos"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb1234"
    volumes:
      - db:/var/lib/mariadb/data
volumes:
  db:
    driver: local